language: go

services:
    - docker
  
go:
    - 1.12.x
before_script:
    - sed  -i -e  's/<VERSION>/1.0.0-beta.1/g' -e  's/<BUILDNUM>/${TRAVIS_BUILD_NUMBER}/g' docker-compose.test.yml 
script:
    - docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit 
after_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push linksmart/historical-datastore
     
