services:
    - docker
 
before_script:
    - sed  -i -e  's/<VERSION>/${TRAVIS_BRANCH}/g' -e  's/<BUILDNUM>/${TRAVIS_BUILD_NUMBER}/g' docker-compose.test.yml 
script:
    - docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit 

before_deploy:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
    - provider: script
      script: docker push linksmart/historical-datastore:latest
      on:
        branch: master
    - provider: script   
      script: docker tag linksmart/historical-datastore linksmart/historical-datastore:${TRAVIS_TAG} &&
                 docker push linksmart/historical-datastore:${TRAVIS_TAG}
      on:
        tags: true
      