version: '2.3'

services:
  hds:
    image: linksmart/historical-datastore
#    build:
#      context: .
    ports:
      - "8085:8085"
    volumes:
      - ./volumes/hds/data:/data
      # - ./volumes/hds/conf:/conf
    restart: unless-stopped
#    command: ["-conf", "/conf/myconf.json"]
